### ISSUE TITLE
link from erlang.org to Secure Coding Guidelines

### ISSUE THREAD

**Issue by max-au** [erlef/security-wg#19]
Action item from the Security WG meeting.
It might be useful to have security-related pages on the erlang.org itself, but some specific recommendations may not be applicable to all OTP builds and version.
One way to solve it is to have a link from erlang.org to Secure Coding guidelines, similar to links to various books and guides.

**Comment by maennchen** [comment]
We should probably pick this idea back up.

A simple PR to this [file](https://github.com/erlang/erlang-org/blob/master/_data/doc-links.yaml) will show it [here](https://www.erlang.org/docs).

How about this?

```yml
  - name: Secure Coding and Deployment Hardening Guidelines
    description: Best-practices for writing and running applications on the BEAM, by the Erlang Ecosystem Foundation’s Security Working Group.
    link: https://erlef.github.io/security-wg/secure_coding_and_deployment_hardening/
```
